name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: make test
